WIP: test cases for plio_uuid
avantifellows/plio-backend pull request #194
Opened 2021-06-18 12:13 UTC by dalmia

Fixes #193 

## Summary
- tests for `list_uuid`

## Test Plan
WIP
- [ ] Wrote tests
- [ ] Tested locally
- [ ] Tested on staging
- [ ] Tested on production
- [ ] If changes in DB, update [DB schema](https://docs.google.com/presentation/d/15c45HbHphh4w3guaFV3BgEA5nMKd-4J35JdUKdrpPzo/edit#slide=id.gc8c9ec0b5e_0_0)

2021-06-18 12:13 UTC, pep8speaks commented
Hello @dalmia! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`plio/tests.py`](https://github.com/avantifellows/plio-backend/blob/55a919ad031f636c42c2e7a210d34cfd7c077754/plio/tests.py):

> [Line 107:80](https://github.com/avantifellows/plio-backend/blob/55a919ad031f636c42c2e7a210d34cfd7c077754/plio/tests.py#L107): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (86 > 79 characters)
> [Line 126:80](https://github.com/avantifellows/plio-backend/blob/55a919ad031f636c42c2e7a210d34cfd7c077754/plio/tests.py#L126): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (84 > 79 characters)

2021-06-18 21:28 UTC, dalmia commented on plio/tests.py
> +    # before merge, update Vaibhav's changes for org and new user - use
this has been kept as a reminder based on whether Vaibhav's or this PR gets merged first. Will remove it before merging.

2021-06-19 08:16 UTC, deepansh96 requested changes

2021-06-19 08:16 UTC, deepansh96 commented on plio/tests.py
> +        new_plio = Plio.objects.create(
If writing this test, the test `test_user_can_list_items` is redundant right?

2021-06-19 08:16 UTC, deepansh96 commented on plio/tests.py
> +    def test_user_can_list_own_items_org(self):
```suggestion
    def test_org_user_can_list_own_items(self):
```
I think this is more clear

2021-06-19 08:16 UTC, deepansh96 commented on plio/tests.py
> +        # get plios
```suggestion
        # get items
```

2021-06-19 08:16 UTC, deepansh96 commented on plio/tests.py
> +        # the plio created above should be listed
```suggestion
        # the item created above should be listed
```

2021-06-19 08:16 UTC, deepansh96 commented on plio/tests.py
> +    def test_user_can_list_other_items_org(self):
```suggestion
    def test_org_user_can_list_other_user_items(self):
```

2021-06-19 08:16 UTC, deepansh96 commented on plio/tests.py
> +    def test_duplicate_own_question(self):
`test_cannot_duplicate_other_user_question`
This test case is not there right?

2021-06-19 09:26 UTC, merged