Add support for checkbox questions
avantifellows/plio-backend pull request #258
Opened 2021-11-25 08:56 UTC by dalmia

Fixes #{issue id}

## Summary

## Test Plan

- [ ] Wrote tests
- [ ] Tested locally
- [ ] Tested on staging
- [ ] Tested on production
- [ ] If changes in DB, update [DB schema](https://docs.google.com/presentation/d/15c45HbHphh4w3guaFV3BgEA5nMKd-4J35JdUKdrpPzo/edit#slide=id.gc8c9ec0b5e_0_0) and BigQuery (staging and prod)

2021-12-09 07:57 UTC, dalmia commented on plio/models.py
> +    correct_answer = models.JSONField(null=True)
sent on discord DM

2021-12-09 07:57 UTC, dalmia commented on entries/models.py
> +    answer = models.JSONField(null=True)
sent on discord DM

2021-12-10 08:59 UTC, dalmia commented on plio/static/plio/docs/download_csv_README.md
> +    For `question_type = checkbox`, it contains a list of indices corresponding to the options which are correct. Here, `answer = [2,3]` indicates that the second and third options have been marked a
update example to add checkbox to table + add new column of question_type

2021-12-15 05:16 UTC, deepansh96 requested changes

2021-12-15 05:16 UTC, deepansh96 commented on plio/static/plio/docs/download_csv_README.md
> +    For `question_type = checkbox`, it contains a list of indices corresponding to the options which are correct. In this case, `question_correct_answer = [2,3]` indicates that the second and third o
This case is not present in the example below no?
Also in the example below, I noticed a typo. MCQ is written as MCC

2021-12-15 08:22 UTC, merged