NEW: endpoints for plio's settings and user's settings
avantifellows/plio-backend pull request #282
Opened 2021-12-22 15:36 UTC by deepansh96

Fixes #281 
Requires [this]() to be merged

## Summary

## Test Plan

- [ ] Wrote tests
- [ ] Tested locally
- [ ] Tested on staging
- [ ] Tested on production
- [ ] If changes in DB, update [DB schema](https://docs.google.com/presentation/d/15c45HbHphh4w3guaFV3BgEA5nMKd-4J35JdUKdrpPzo/edit#slide=id.gc8c9ec0b5e_0_0) and BigQuery (staging and prod)

2021-12-22 15:36 UTC, pep8speaks commented
Hello @deepansh96! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`plio/views.py`](https://github.com/avantifellows/plio-backend/blob/24b7e73d72d356bdd8e313e0e9a7c2130d3f22b3/plio/views.py):

> [Line 130:21](https://github.com/avantifellows/plio-backend/blob/24b7e73d72d356bdd8e313e0e9a7c2130d3f22b3/plio/views.py#L130): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 131:46](https://github.com/avantifellows/plio-backend/blob/24b7e73d72d356bdd8e313e0e9a7c2130d3f22b3/plio/views.py#L131): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace

* In the file [`users/views.py`](https://github.com/avantifellows/plio-backend/blob/24b7e73d72d356bdd8e313e0e9a7c2130d3f22b3/users/views.py):

> [Line 49:21](https://github.com/avantifellows/plio-backend/blob/24b7e73d72d356bdd8e313e0e9a7c2130d3f22b3/users/views.py#L49): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 50:46](https://github.com/avantifellows/plio-backend/blob/24b7e73d72d356bdd8e313e0e9a7c2130d3f22b3/users/views.py#L50): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 58:1](https://github.com/avantifellows/plio-backend/blob/24b7e73d72d356bdd8e313e0e9a7c2130d3f22b3/users/views.py#L58): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace

Do see the [Hitchhiker's guide to code style](https://goo.gl/hqbW4r)

2022-01-05 06:08 UTC, dalmia requested changes

2022-01-05 06:08 UTC, dalmia commented on plio/tests.py
> +
any reason why a new plio was created for this?

2022-01-05 06:08 UTC, dalmia commented on plio/tests.py
> +            json.loads(test_settings),
`json.loads(json.dumps(X)) = X` right?

2022-01-25 12:11 UTC, dalmia requested changes

2022-01-25 12:11 UTC, dalmia commented on users/tests.py
> +        # The plio should contain the new updated settings object
we have generally not including capital letters in general comment sentences
```suggestion
        # the plio should contain the new updated settings object
```

2022-01-25 12:11 UTC, dalmia commented on users/tests.py
> +        )
same point about json.dumps and json.loads being redundant

2022-01-25 12:11 UTC, dalmia commented on users/tests.py
> +        # Forbidden action
```suggestion
        # forbidden action
```

2022-01-25 12:11 UTC, dalmia commented on users/tests.py
> +        # 200 OK returned as status
i don't think we need to write comments for every single action/line - this is fairly obvious - let's remove it?

2022-01-25 12:11 UTC, dalmia commented on users/tests.py
> +        # make user 1 the superuser
i don't think we need to write comments for every single action/line - this is fairly obvious - let's remove it?

2022-01-25 12:11 UTC, dalmia commented on users/tests.py
> +        # try the request again
i don't think we need to write comments for every single action/line - this is fairly obvious - let's remove it?

2022-01-25 12:11 UTC, dalmia commented on plio/tests.py
> +        )
any reason why a new plio was created for this?

2022-01-25 12:11 UTC, dalmia commented on plio/tests.py
> +        )
same point about json.dumps and json.loads being redundant?

2022-01-25 12:11 UTC, dalmia commented on plio/tests.py
> +
same point about json.dumps and json.loads being redundant?

2022-01-25 12:11 UTC, dalmia commented on plio/tests.py
> +        # Updating other user's plio's settings should be forbidden
```suggestion
        # updating other user's plio's settings should be forbidden
```

2022-01-25 12:11 UTC, dalmia commented on plio/tests.py
> +        )
same point about json.dumps and json.loads being redundant?

2022-01-25 12:11 UTC, dalmia commented on organizations/tests.py
> +        """ /settings/ action only supports PUT method """
i think we have started the right thing of not unnecessarily writing docstrings for tests when the function name makes it obvious. so, let's remove this?

2022-01-25 12:11 UTC, dalmia commented on organizations/tests.py
> +        """A superuse is allowed to update settings of any org"""
same point about redundant docstring in tests

2022-01-25 12:11 UTC, dalmia commented on organizations/tests.py
> +        )
what extra is this checking?

2022-01-25 12:11 UTC, dalmia commented on organizations/tests.py
> +        superuser_client = APIClient()
why not use self.client?

2022-01-28 06:35 UTC, deepansh96 commented on organizations/views.py
> +    def setting(self, request, pk):
https://github.com/encode/django-rest-framework/issues/3337

`settings` is a keyword reserved for Django so we cannot use that name in a view

2022-01-28 06:35 UTC, deepansh96 commented on plio/views.py
> +    def setting(self, request, uuid):
same comment as above

2022-01-28 06:35 UTC, deepansh96 commented on users/views.py
> +    def setting(self, request, pk):
same comment as above

2022-01-28 08:50 UTC, dalmia commented on organizations/views.py
> +        """Updates an org's settings key inside it's config"""
similar to what we did for plio

```suggestion
        """Updates an org's settings"""
```

2022-01-28 08:50 UTC, dalmia commented on users/views.py
>          """Updates a user's setting key inside it's config"""
```suggestion
        """Updates a user's settings"""
```

2022-01-28 08:50 UTC, dalmia commented on organizations/tests.py
> +        superuser_client = APIClient()
do drop a comment about this

2022-01-28 09:00 UTC, dalmia requested changes

2022-01-31 06:10 UTC, deepansh96 commented on organizations/views.py
> +            self.get_serializer(org).data["config"], status=status.HTTP_200_OK
```suggestion
            self.get_serializer(org).data["config"]
```

2022-02-08 05:12 UTC, dalmia approved these changes

2022-02-09 11:34 UTC, merged