added check for removing CMS_TOKEN
avantifellows/plio-backend pull request #305
Opened 2022-01-19 16:11 UTC by Salonichoudhary07

Fixes #297 

## Summary

CMS_TOKEN was not being used at the backend.

## Test Plan

- [ ] Wrote tests
- [ ] Tested locally
- [ ] Tested on staging
- [ ] Tested on production
- [ ] If adding any new environment variable:
    - [ ] update `docs/ENV.md`
    - [ ] update the environment variables for staging and production
- [ ] If changes in DB, update [DB schema](https://docs.google.com/presentation/d/15c45HbHphh4w3guaFV3BgEA5nMKd-4J35JdUKdrpPzo/edit#slide=id.gc8c9ec0b5e_0_0) and BigQuery (staging and prod)

2022-01-19 16:18 UTC, deepansh96 requested changes
Minor changes

2022-01-19 16:18 UTC, deepansh96 commented on .env.example
> +SECRET_KEY='i%&w001-tkaz_f&r#=1%9^90eaqdhu1byjjx#11n*zf&ua@s9@' # generate from https://djecrety.ir/
I think you forgot to remove this value.
This secret key's value should not be present in `.env.example` file. This file is supposed to be just an example. Everyone's secret key would be different and stored in their personal `.env` file

2022-01-19 16:18 UTC, deepansh96 commented on docs/ENV.md
> +
Extra line

2022-01-19 16:18 UTC, deepansh96 commented on .env.example
> +
Extra line

2022-01-20 06:57 UTC, dalmia approved these changes

2022-01-20 06:57 UTC, merged